security:
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ttckUserBundle\Entity\User: bcrypt

    providers:
         main:
            entity:
                class: ttckUserBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: false
                default_target_path: index
            logout:
                path: /logout
                target: /ttck


    role_hierarchy:
          ROLE_ADMIN : [ROLE_VISITEUR , ROLE_EQUIPE , ROLE_ARTICLE]
          ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]
